version: '3.1'

services:

  wordpress:
    image: wordpress
    restart: always
    ports:
      - 8080:80
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: ai-alt-text_user
      WORDPRESS_DB_PASSWORD: ai-auto-alt_password
      WORDPRESS_DB_NAME: wp_auto_alt_db
    
    # The development environment is mounted to the local directory for faster development
    volumes:
      - ./wordpress:/var/www/html  # Mount the entire WordPress directory

      # Mount our plugin under development
      - ../wordpress/wp-content/plugins/ai-auto-alt:/var/www/html/wp-content/plugins/ai-auto-alt

      # Mount the wp-config.php file to be editable outside of the container
      - ../wordpress/wp-config.php:/var/www/html/wp-config.php

      # Mount the debug log
      - ../wordpress/wp-content/debug.log:/var/www/html/wp-content/debug.log

  db:
    image: mariadb:11.2.2
    restart: always
    environment:
      MARIADB_DATABASE: wp_auto_alt_db
      MARIADB_USER: ai-alt-text_user
      MARIADB_PASSWORD: ai-auto-alt_password
      MARIADB_ROOT_PASSWORD: ai-auto-alt

    # The development database is mounted to the local directory
    # In general this directory should not have updated commits
    volumes:
      - ./data/db:/var/lib/mysql

volumes:
  wordpress:
  db: